CREATE TABLE IF NOT EXISTS carts
(
cart_id INT AUTO_INCREMENT PRIMARY KEY,
user_id BINARY(16) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
cart_status ENUM('active', 'abandoned', 'executed') NOT NULL DEFAULT 'active',
FOREIGN KEY (user_id) REFERENCES users(user_id)
)