CREATE TABLE IF NOT EXISTS users
(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL UNIQUE,
username VARCHAR(25) NOT NULL UNIQUE,
email VARCHAR(80) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
last_online_at DATETIME DEFAULT CURRENT_TIMESTAMP,
is_active TINYINT(1) UNSIGNED DEFAULT 1,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES user_full_data(id) ON DELETE CASCADE
)