CREATE TABLE IF NOT EXISTS carts
(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
cart_status ENUM('active', 'abandoned', 'executed') NOT NULL DEFAULT 'active',
FOREIGN KEY (user_id) REFERENCES users(id)
)